id: PDF53D527
initial_creation_type: input
source_metadata:
  Title: Atishavirachita Ekadasa grantha
  Editor: Negi, Ramesh Chandra.
  Publisher: Central Institute of Higher Tibetan Studies
  Place of Publication: Sarnath
  Year: '1992'
  Āpattideśanāvidhiḥ:
    Text Version: Romanized
    Input Personnel: DSBC Staff
    Input Date: '2006'
    Proof Reader: Milan Shakya
    Supplier: Nagarjuna Institute of Exact Methods
    Sponsor: University of the West
created_at: '2022-03-08T16:41:30.838906'
last_modified_at: '2022-03-08T16:41:30.838913'
